name: contraflutterkit
description: Flutter application built on top of contra wireframe kit.


version: 1.0.0+1


environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0-nullsafety.0
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  flutter_time_picker_spinner: ^1.0.6+1
  charts_flutter: ^0.9.0
  fl_chart: ^0.20.1
  google_maps_flutter: ^2.0.1
  flutter_swiper: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/images/shopping/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
  uses-material-design: true

